# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    (
        b'\n\x10permission.proto\x12\npermission"?\n\x11\x41\x63\x63\x65ssibleRequest\x12\r\n\x05'
        b'token\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t"<'
        b'\n\x12\x41\x63\x63\x65ssibleResponse\x12\x15\n\ris_accessible\x18\x01 \x01(\x08\x12\x0f\n\x07'
        b'message\x18\x02 \x01(\t2^\n\nPermission\x12P\n\ris_accessible\x12\x1d.permission.Accessible'
        b'Request\x1a\x1e.permission.AccessibleResponse"\x00\x62\x06proto3'
    )
)


_ACCESSIBLEREQUEST = DESCRIPTOR.message_types_by_name['AccessibleRequest']
_ACCESSIBLERESPONSE = DESCRIPTOR.message_types_by_name['AccessibleResponse']
AccessibleRequest = _reflection.GeneratedProtocolMessageType(
    'AccessibleRequest',
    (_message.Message,),
    {
        'DESCRIPTOR': _ACCESSIBLEREQUEST,
        '__module__': 'permission_pb2'
        # @@protoc_insertion_point(class_scope:permission.AccessibleRequest)
    },
)
_sym_db.RegisterMessage(AccessibleRequest)

AccessibleResponse = _reflection.GeneratedProtocolMessageType(
    'AccessibleResponse',
    (_message.Message,),
    {
        'DESCRIPTOR': _ACCESSIBLERESPONSE,
        '__module__': 'permission_pb2'
        # @@protoc_insertion_point(class_scope:permission.AccessibleResponse)
    },
)
_sym_db.RegisterMessage(AccessibleResponse)

_PERMISSION = DESCRIPTOR.services_by_name['Permission']
if _descriptor._USE_C_DESCRIPTORS is False:

    DESCRIPTOR._options = None
    _ACCESSIBLEREQUEST._serialized_start = 32
    _ACCESSIBLEREQUEST._serialized_end = 95
    _ACCESSIBLERESPONSE._serialized_start = 97
    _ACCESSIBLERESPONSE._serialized_end = 157
    _PERMISSION._serialized_start = 159
    _PERMISSION._serialized_end = 253
# @@protoc_insertion_point(module_scope)
