# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import permission_pb2 as permission__pb2


class PermissionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.is_accessible = channel.unary_unary(
                '/permission.Permission/is_accessible',
                request_serializer=permission__pb2.AccessibleRequest.SerializeToString,
                response_deserializer=permission__pb2.AccessibleResponse.FromString,
                )


class PermissionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def is_accessible(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PermissionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'is_accessible': grpc.unary_unary_rpc_method_handler(
                    servicer.is_accessible,
                    request_deserializer=permission__pb2.AccessibleRequest.FromString,
                    response_serializer=permission__pb2.AccessibleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'permission.Permission', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Permission(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def is_accessible(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/permission.Permission/is_accessible',
            permission__pb2.AccessibleRequest.SerializeToString,
            permission__pb2.AccessibleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
